=== ethereum-lists/chains/tools/schema/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","shortName","chain","chainId","networkId","rpc","faucets","infoURL","nativeCurrency"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "shortName":{
            "type":"string",
            "pattern": "^[A-Za-z0-9-_]{1,64}$"
        },
        "title":{
            "type":"string",
            "description": "Optional title for the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "features":{
	    "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string",
			"description": "feature name - e.g. EIP155"
                    }
                }
	    }
	},
        "nativeCurrency":{	    
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string",
			"description": "EIP3091 or none"
                    }
                }
            }
        },
        "parent":{
            "type":"object",
            "properties": {
                "type":{
                    "type":"string"
                },
                "chain":{
                    "type":"string"
                },
                "bridges":{
                    "type":"array",
                    "items": {
                        "type":"object",
                        "properties":{
                            "url": {
                                "type":"string"
                            }
                        }
                    }
                }
            }
        },
        "status":{
            "type":"string"
        },
        "redFlags":{
            "type":"array",
            "items":{
                "type":"string",
                "enum": ["reusedChainId"]
            }
           
        }
    },
    "additionalProperties": false
}

=== ethereum-lists/chains/_data/chains/eip155-5611.json
{
  "name": "opBNB Testnet",
  "chain": "opBNB",
  "icon": "bnbchain",
  "rpc": [
    "https://opbnb-testnet-rpc.bnbchain.org",
    "https://opbnb-testnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3",
    "wss://opbnb-testnet.nodereal.io/ws/v1/64a9df0874fb4a93b9d0a3849de012d3",
    "https://opbnb-testnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5",
    "wss://opbnb-testnet.nodereal.io/ws/v1/e9a36765eb8a40b9bd12e680a1fd2bc5",
    "https://opbnb-testnet-rpc.publicnode.com",
    "wss://opbnb-testnet-rpc.publicnode.com"
  ],
  "faucets": ["https://testnet.bnbchain.org/faucet-smart"],
  "nativeCurrency": {
    "name": "BNB Chain Native Token",
    "symbol": "tBNB",
    "decimals": 18
  },
  "infoURL": "https://opbnb.bnbchain.org/en",
  "shortName": "obnbt",
  "chainId": 5611,
  "networkId": 5611,
  "slip44": 1,
  "explorers": [
    {
      "name": "bscscan-opbnb-testnet",
      "url": "https://opbnb-testnet.bscscan.com",
      "standard": "EIP3091"
    },
    {
      "name": "opbnbscan",
      "url": "https://opbnbscan.com",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-43114.json
{
  "name": "Avalanche C-Chain",
  "chain": "AVAX",
  "icon": "avax",
  "rpc": [
    "https://api.avax.network/ext/bc/C/rpc",
    "https://avalanche-c-chain-rpc.publicnode.com",
    "wss://avalanche-c-chain-rpc.publicnode.com",
    "https://rpc.swiftnodes.io/rpc/avalanche"
  ],
  "features": [
    {
      "name": "EIP1559"
    }
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Avalanche",
    "symbol": "AVAX",
    "decimals": 18
  },
  "infoURL": "https://www.avax.network/",
  "shortName": "avax",
  "chainId": 43114,
  "networkId": 43114,
  "slip44": 9005,
  "explorers": [
    {
      "name": "Etherscan",
      "url": "https://snowscan.xyz",
      "standard": "EIP3091"
    },
    {
      "name": "Routescan",
      "url": "https://snowtrace.io",
      "standard": "EIP3091"
    },
    {
      "name": "Avascan",
      "url": "https://avascan.info",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-5371.json
{
  "name": "Settlus",
  "chain": "ETH",
  "rpc": ["https://settlus-mainnet.g.alchemy.com/public"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://settlus.org",
  "shortName": "setl",
  "chainId": 5371,
  "networkId": 5371,
  "parent": {
    "type": "L2",
    "chain": "eip155-1",
    "bridges": [{ "url": "https://settlus-mainnet.bridge.alchemy.com/" }]
  },
  "explorers": [
    {
      "name": "Settlus Mainnet Explorer",
      "url": "https://mainnet.settlus.network",
      "standard": "EIP3091"
    }
  ],
  "status": "active"
}

=== ethereum-lists/chains/_data/chains/eip155-100000.json
{
  "name": "QuarkChain Mainnet Root",
  "chain": "QuarkChain",
  "rpc": ["http://jrpc.mainnet.quarkchain.io:38391"],
  "faucets": [],
  "nativeCurrency": {
    "name": "QKC",
    "symbol": "QKC",
    "decimals": 18
  },
  "infoURL": "https://www.quarkchain.io",
  "shortName": "qkc-r",
  "chainId": 100000,
  "networkId": 100000
}

=== ethereum-lists/chains/_data/chains/eip155-3500.json
{
  "name": "Paribu Net Testnet",
  "chain": "PRB",
  "rpc": ["https://rpc.testnet.paribuscan.com"],
  "faucets": ["https://faucet.paribuscan.com"],
  "nativeCurrency": {
    "name": "PRB",
    "symbol": "PRB",
    "decimals": 18
  },
  "infoURL": "https://net.paribu.com",
  "shortName": "prbtestnet",
  "chainId": 3500,
  "networkId": 3500,
  "slip44": 1,
  "icon": "prb",
  "explorers": [
    {
      "name": "Paribu Net Testnet Explorer",
      "url": "https://testnet.paribuscan.com",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-686868.json
{
  "name": "Won Network",
  "chainId": 686868,
  "shortName": "WonChain",
  "chain": "WON",
  "icon": "won",
  "networkId": 686868,
  "nativeCurrency": {
    "name": "Won",
    "symbol": "WON",
    "decimals": 18
  },
  "rpc": ["https://rpc.wonnetwork.org"],
  "faucets": ["https://faucet.wondollars.org"],
  "explorers": [
    {
      "name": "Won Explorer",
      "url": "https://scan.wonnetwork.org",
      "standard": "EIP3091"
    }
  ],
  "infoURL": "https://wonnetwork.org"
}

=== ethereum-lists/chains/_data/chains/eip155-19077.json
{
  "name": "BlockX Atlantis Testnet",
  "chain": "blockx",
  "rpc": ["https://atlantis-rpc.blockxnet.com/"],
  "faucets": ["https://ping.blockxnet.com/blockx-atlantis-testnet/faucet"],
  "nativeCurrency": {
    "name": "BCX",
    "symbol": "BCX",
    "decimals": 18
  },
  "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
  "infoURL": "https://www.blockxnet.com/",
  "shortName": "bcx",
  "chainId": 19077,
  "networkId": 19077,
  "explorers": [
    {
      "name": "BlockX EVM Explorer (Blockscout)",
      "url": "https://testnet-explorer.blockxnet.com/",
      "standard": "EIP3091"
    },
    {
      "name": "BlockX Cosmos Explorer (Ping)",
      "url": "https://ping.blockxnet.com/blockx-atlantis-testnet",
      "standard": "none"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-534352.json
{
  "name": "Scroll",
  "chain": "ETH",
  "status": "active",
  "rpc": [
    "https://rpc.scroll.io",
    "https://rpc.ankr.com/scroll",
    "https://scroll-mainnet.chainstacklabs.com",
    "https://scroll-rpc.publicnode.com",
    "wss://scroll-rpc.publicnode.com",
    "https://rpc.swiftnodes.io/rpc/scroll?key=${SWIFTNODES_API_KEY}"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://scroll.io",
  "shortName": "scr",
  "chainId": 534352,
  "networkId": 534352,
  "explorers": [
    {
      "name": "Scrollscan",
      "url": "https://scrollscan.com",
      "standard": "EIP3091"
    }
  ],
  "parent": {
    "type": "L2",
    "chain": "eip155-1",
    "bridges": [{ "url": "https://scroll.io/bridge" }]
  }
}
