=== ethereum-lists/chains/tools/schema/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","shortName","chain","chainId","networkId","rpc","faucets","infoURL","nativeCurrency"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "shortName":{
            "type":"string",
            "pattern": "^[A-Za-z0-9-_]{1,64}$"
        },
        "title":{
            "type":"string",
            "description": "Optional title for the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "features":{
	    "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string",
			"description": "feature name - e.g. EIP155"
                    }
                }
	    }
	},
        "nativeCurrency":{	    
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string",
			"description": "EIP3091 or none"
                    }
                }
            }
        },
        "parent":{
            "type":"object",
            "properties": {
                "type":{
                    "type":"string"
                },
                "chain":{
                    "type":"string"
                },
                "bridges":{
                    "type":"array",
                    "items": {
                        "type":"object",
                        "properties":{
                            "url": {
                                "type":"string"
                            }
                        }
                    }
                }
            }
        },
        "status":{
            "type":"string"
        },
        "redFlags":{
            "type":"array",
            "items":{
                "type":"string",
                "enum": ["reusedChainId"]
            }
           
        }
    },
    "additionalProperties": false
}

=== ethereum-lists/chains/_data/chains/eip155-7244.json
{
  "name": "ZEUS Testnet",
  "chain": "tZEUS",
  "icon": "zeusicon",
  "rpc": ["https://testnet-rpc.zeuschainscan.io"],
  "nativeCurrency": {
    "name": "The ZEUS Token",
    "symbol": "ZEUSX",
    "decimals": 18
  },
  "infoURL": "https://testnet-explorer.zeuschainscan.io",
  "shortName": "ZEUS-Testnet",
  "chainId": 7244,
  "networkId": 7244,
  "faucets": ["https://faucet.zeuschainscan.io"],
  "explorers": [
    {
      "name": "ZEUS Testnet Explorer",
      "url": "https://testnet-explorer.zeuschainscan.io",
      "icon": "zeusicon",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-364.json
{
  "name": "Theta Amber Testnet",
  "chain": "Theta",
  "rpc": ["https://eth-rpc-api-amber.thetatoken.org/rpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Theta Fuel",
    "symbol": "TFUEL",
    "decimals": 18
  },
  "infoURL": "https://www.thetatoken.org/",
  "shortName": "theta-amber",
  "chainId": 364,
  "networkId": 364,
  "slip44": 1,
  "explorers": [
    {
      "name": "Theta Amber Testnet Explorer",
      "url": "https://guardian-testnet-amber-explorer.thetatoken.org",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-4888.json
{
  "name": "BlackFort Exchange Network Testnet",
  "chain": "BXNT",
  "rpc": ["https://rpc.blackfort.network/testnet/rpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "BlackFort Testnet Token",
    "symbol": "BXNT",
    "decimals": 18
  },
  "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
  "infoURL": "https://blackfort.com",
  "shortName": "BXNT",
  "chainId": 4888,
  "networkId": 4888,
  "slip44": 1,
  "icon": "bxn",
  "explorers": [
    {
      "name": "blockscout",
      "url": "https://testnet.blackfortscan.com",
      "icon": "blockscout",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-706883.json
{
  "name": "Fidesinnova",
  "chain": "Fidesinnova",
  "rpc": ["https://rpc1.fidesinnova.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Fidesinnova",
    "symbol": "FDS",
    "decimals": 18
  },
  "infoURL": "https://fidesinnova.gitbook.io/docs",
  "shortName": "Fidesinnova",
  "chainId": 706883,
  "networkId": 706883,
  "explorers": [
    {
      "name": "Fidesinnova Blockchain Explorer",
      "url": "https://explorer.fidesinnova.io",
      "standard": "none"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-18881.json
{
  "name": "Ultra EVM Network Testnet",
  "chain": "Ultra",
  "icon": "ultra",
  "rpc": ["https://evm.test.ultra.eosusa.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ultra Token",
    "symbol": "UOS",
    "decimals": 18
  },
  "infoURL": "https://ultra.io/",
  "shortName": "ultra-testnet",
  "chainId": 18881,
  "networkId": 18881,
  "slip44": 1,
  "explorers": [
    {
      "name": "Ultra EVM Testnet Explorer",
      "url": "https://evmexplorer.testnet.ultra.io",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-128.json
{
  "name": "Huobi ECO Chain Mainnet",
  "chain": "Heco",
  "rpc": [
    "https://http-mainnet.hecochain.com",
    "wss://ws-mainnet.hecochain.com"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Huobi ECO Chain Native Token",
    "symbol": "HT",
    "decimals": 18
  },
  "infoURL": "https://www.hecochain.com",
  "shortName": "heco",
  "chainId": 128,
  "networkId": 128,
  "slip44": 1010,
  "explorers": [
    {
      "name": "hecoinfo",
      "url": "https://hecoinfo.com",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-175.json
{
  "name": "OTC",
  "chain": "OTC",
  "faucets": [],
  "icon": "otc",
  "rpc": ["https://rpc.otc.run", "wss://rpc.otc.run"],
  "nativeCurrency": {
    "name": "OTC",
    "symbol": "OTC",
    "decimals": 18
  },
  "infoURL": "https://otc.network",
  "shortName": "OTC",
  "chainId": 175,
  "networkId": 175,
  "slip44": 511
}

=== ethereum-lists/chains/_data/chains/eip155-20994.json
{
  "name": "Fluent Testnet",
  "chain": "Fluent",
  "rpc": ["https://rpc.testnet.fluent.xyz/"],
  "faucets": ["https://testnet.gblend.xyz/"],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://fluent.xyz",
  "shortName": "fluent-testnet",
  "chainId": 20994,
  "networkId": 20994,
  "explorers": [
    {
      "name": "Fluent Blockscout Explorer",
      "url": "https://testnet.fluentscan.xyz",
      "standard": "EIP3091"
    }
  ]
}
